package domrbeeson.gamma.network.packet;

public enum Packet {
    KEEP_ALIVE(0),
    LOGIN(1),
    HANDSHAKE(2),
    CHAT(3),
    TIME(4),
    ENTITY_EQUIPMENT(5),
    SPAWN_POSITION(6),
    ENTITY_USE(7),
    PLAYER_HEALTH(8),
    PLAYER_RESPAWN(9),
    FLYING(10),
    PLAYER_POSITION(11),
    PLAYER_LOOK(12),
    PLAYER_POSITION_AND_LOOK(13),
    PLAYER_DIGGING(14),
    PLAYER_BLOCK_PLACE(15),
    PLAYER_HELD_ITEM_CHANGE(16),
    PLAYER_USE_BED(17),
    PLAYER_ANIMATION(18),
    ENTITY_ACTION(19),
    PLAYER_SPAWN(20),
    ITEM_SPAWN(21),
    ENTITY_PICK_UP_ITEM(22),
    OBJECT_SPAWN(23),
    LIVING_ENTITY_SPAWN(24),
    ENTITY_VELOCITY(28),
    ENTITY_DESTROY(29),

    ENTITY_RELATIVE_MOVE(31),
    ENTITY_LOOK(32),
    ENTITY_RELATIVE_MOVE_AND_LOOK(33),
    ENTITY_TELEPORT(34),

    ENTITY_METADATA(40),


    PRE_CHUNK(50),
    CHUNK(51),
    MULTI_BLOCK_CHANGE(52),
    BLOCK_CHANGE(53),
    NOTE_BLOCK(54),

    EXPLOSION(60),

    INVALID_STATE(70),
    WEATHER(71),

    OPEN_WINDOW(100),
    CLOSE_WINDOW(101),
    WINDOW_CLICK(102),
    PLAYER_INVENTORY_SLOT(103),
    WINDOW_ITEMS(104),
    WINDOW_PROGRES_BAR(105),

    PLAYER_KICK(255),
    ;

    public final int id;

    Packet(int id) {
        this.id = id;
    }
}
